name: Dart CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: 'stable'
      - name: init env
        run: |
          flutter pub get
          export JPUSH_KEY=${{ secrets.JPUSH_KEY }}
          echo >> android/local.properties 'JPUSH_KEY=${{ secrets.JPUSH_KEY }}'
      # - run: echo >> lib/_key.dart 'const UMENG_KEY = "${{ secrets.UMENG_KEY }}";'
      - name: build adnroid apk
        run: |
          flutter build apk --release -v
      - name: upload apk
        run: |
          git config --global user.name ${{ secrets.GIT_USER_NAME }}
          git config --global user.email ${{ secrets.GIT_EMAL }}
          git clone https://${{ secrets.GH_TOKEN }}@github.com/cliclitv/app.clicli.me.git
          cd ./app.clicli.me
          mv ../build/app/outputs/apk/release/* ./
          git add -A && git commit -m 'update release'
          git push -f https://${{ secrets.GH_TOKEN }}@github.com/cliclitv/app.clicli.me.git
      - name: build flutter web
        run: |
          flutter build web --release -v
      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
