name: Dart CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: 'stable'
      - name: init env
        run: |
          flutter pub get
      - name: build adnroid apk
        run: |
          flutter build apk --release -v
      - name: upload apk
        run: |
          git clone https://github.com/cliclitv/app.clicli.me.git
          cd ./app.clicli.me
          mv ../build/app/outputs/apk/release/* ./
          git add -A && git commit -m 'update release'
          git push -f https://github.com/cliclitv/app.clicli.me.git
      - name: build flutter web
        run: |
          flutter build web --release -v
      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./build/web
          publish_branch: gh-pages